#!/bin/bash
#========================================================
# Script Name: hmenu
# By: CK
# Date: 11/7/24
# Purpose: A menu for the Hospital Database
# Command Line: hmenu
#========================================================
trap "rm ./f 2> /dev/null; exit" 0 1 3
patientfile=~/capstone/patient.csv
loop=y
while test $loop = "y" 
do
clear
bold=`tput smso` #set standout mode - bold
offbold=`tput rmso` #reset screen turn bold off
tput cup 3 12; echo -e $bold  "\033[95mWelcome to the Hospital Database Menu\033[0m"
tput cup 4 9; echo $offbold  "============================================"
tput cup 6 9; echo "[L/l] List Patients"
tput cup 7 9; echo "[A/a] Add New Patient"
tput cup 8 9; echo "[S/s] Search for Patient"
tput cup 9 9; echo "[D/d] Delete Patient"
tput cup 10 9; echo "[E/e] Exit"
read choice || continue
case $choice in
	[Ll]) ./listpatients ;;
	[Aa]) ./addpatient ;;
	[Ss]) ./searchp ;;
	[Dd])   tput cup 16 4; echo "Delete Patient Record"
		tput cup 17 4; echo "Enter Patient's Last Name: "
		tput cup 17 30; read lname
		tput cup 19 5; echo "Delete $fname $lname. Accept (y)es or (n)o: "
		tput cup 20 5; read Accept
		if test $Accept = "y"
		then
			sed /$lname/d $patientfile > f
			cp f $patientfile
			rm f
		fi;;	
	[Ee]) echo "Thank you for using the app"; read anykey ;  exit ;;
	*) tput cup 14 4; echo "Invalid Code, Press Any Key to Continue"; read anykey ;;
	esac
done

